on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  solve:
    name: Solve
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1.0.5
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Solve the puzzle
        run: |
          google-chrome --version
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub --port=4444 &
          cargo run --bin solve
